### ISSUE TITLE
Error while running: lead: error while loading shared libraries: libQt5Xdg.so.2: cannot open shared object file: No such file or directory

### ISSUE THREAD

**Issue by SwimminglyWell** [mlde/lead#7]

**Comment by Almamu** [comment]
You are missing one of the dependencies, in the case of debian:
https://packages.debian.org/sid/libqt5xdg-dev
You'll have to find the equivalent package on your chosen distro if it's not debian.

**Comment by SwimminglyWell** [comment]
I'm using a flavour of ubuntu 18.04, and I do have this package installed, at least the version available through the ubuntu repositories. Checked again and still got the same error.
