### ISSUE TITLE
Sarcastic first-world problem: Lead for FreeBSD

### ISSUE THREAD

**Issue by schijtreiger** [mlde/lead#9]
I modified your 'makefile' so that it plays nice & builds on FreeBSD. It is a bit hacky & I'm sure somebody will be able to modify it in a much more elegant fashion. See attached:

[freebsd-friendly-makefile.txt](https://github.com/mlde/lead/files/4222710/freebsd-friendly-makefile.txt)

 Tested on FreeBSD-12.1 & FreeBSD-13.0 (-CURRENT)
 Heads up: gmake is REQUIRED here to build. Ports lang/gcc8 or lang/gcc9
 Packages / Ports required:  x11-toolkits/qt5-widgets | x11-toolkits/qt5-gui | devel/qt5-core | devel/libqtxdg

 Basically all that was required was to reflect the FreeBSD ecosystem
 userland directory file structure, with '/usr/local/<dir-name>' & the addition
 of '-lstdc++'  switch to the g++ compiler commandline.
 Depending on how you have LD set up, you may or may not get complaints
 from g++ about missing Qt5* libraries (occurred when building on FreeBSD-13.0).
 A quick-n-dirty 'ln -s' will  suffice in this instance, without any harm (substitute 'doas' with 'sudo' if you haven't got 'doas' installed): 
 'doas ln -s /usr/local/lib/qt5/libQt5Widgets.so /usr/local/lib/libQt5Widgets.so'
 'doas ln -s /usr/local/lib/qt5/libQt5Gui.so /usr/local/lib/libQt5Gui.so'
 'doas ln -s /usr/local/lib/qt5/libQt5Core.so /usr/local/lib/libQt5Core.so'

Captain Obvious instructions: backup the original 'makefile' when cloning this lead repo && rename the FreeBSD-friendly version I've attached here to 'makefile' (or Makefile if your OCD requires)

Edit $HOME/.config/lead/lead.conf  to your needs. I use 'skippy-xd' for 'topLeft'

**Comment by nullraum** [comment]
thank you for your contribution!
